version: 1.7.0.{build}
image: Visual Studio 2019
branches:
  only:
  - master
skip_tags: true
platform: Any CPU
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: dotnet --version
- ps: dotnet restore
build:
  project: SQLite.CodeFirst.sln
  parallel: true
  verbosity: normal
artifacts:
- path: SQLite.CodeFirst\bin
  name: Assemblies
- path: SQLite.CodeFirst\bin\Release\*.nupkg
  name: NuPkg
deploy:
# Encrypt with https://ci.appveyor.com/tools/encrypt
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: v$(appveyor_build_version)
  description: https://www.nuget.org/packages/SQLite.CodeFirst/
  auth_token:
    secure: /EbrWy9O9cuWEzo1mZZFJ/v6yonU4k5HWKYXsTKdsP72o1M7b23pHcsczVVvIRFGcrNAh9jIh8+e01zA8HgmlVVebzBVe1pBN/XJb+Q71gG6XvPu0SHQPSm+M+jqgbkI
  artifact: Assemblies,NuPkg
  draft: true
  on:
    branch: master